# sources: http://www.atrixnet.com/bs-generator.html
#          https://en.wikipedia.org/wiki/List_of_buzzwords
#          http://cbsg.sourceforge.net/cgi-bin/live
BUZZWORDS = {
    'en': ['as a tier 1 company', 'paving the way for', 'relative to our peers', '-free', '200%', '24/365',
        '24/7', '360-degree', '360-degree thinking', '50/50', '99.9', 'ability to deliver', 'ability to move fast',
        'above-average', 'accelerate', 'accelerate the strategy', 'accelerated', 'accelerating', 'accepted',
        'accessible', 'accomplishment', 'account executive', 'accountability', 'accountable talk', 'acculturated',
        'accurate', 'achieve', 'achieve efficiencies', 'across and beyond the', 'across geographies',
        'across industry sectors', 'across our portfolio', 'across the', 'across the board',
        'across the wider group', 'action forward', 'action item', 'action items', 'action plan', 'actionable',
        'activate', 'active differentiation', 'actualize', 'adapt', 'adaptability', 'adaptive', 'address',
        'address the overarching issues', 'adequate', 'adequately', 'administrate', 'adoptable', 'aggregate',
        'aggregator', 'aggressive', 'aggressively', 'agile', 'agility', 'agreed-upon', 'ahead of schedule', 'alert',
        'align resources', 'aligned', 'alignment', 'alternative', 'an expanded array of', 'analyse', 'analytic',
        'analytics', 'analytics-based', 'applications', 'appropriately', 'architect', 'architectural approach',
        'architecture', 'articulate', 'as a consequence of', 'as part of the plan', 'aspirations', 'assertive',
        'asset', 'at the end of the day', 'at the individual, team and organizational level', 'atmosphere',
        'attitude', 'attractive-enough', 'attractiveness', 'authoritatively', 'avoid', 'awareness', 'awesome', 'b2b',
        'b2c', 'backward-compatible', 'balanced', 'balanced scorecard', 'ballpark figure', 'bandwidth', 'barriers',
        'barriers to success', 'baseline starting point', 'be cautiously optimistic', 'be committed', 'because',
        'benchmark', 'benchmark the portfolio', 'benchmarking', 'benefit', 'benefits', 'best of breed',
        'best practice', 'best practices', 'best-in-class', 'best-of-breed', 'best-of-class', 'better-than-planned',
        'bi-face', 'big data', 'big picture', 'big society', 'big-picture thinking', 'bizmeth', 'black swans',
        'bleeding edge', 'bleeding-edge', 'blended approach', "bloom's taxonomy", 'board-level executives',
        'book value growth', 'boost', 'bottom line', 'bottom-up', 'boundaryless', 'brand identity', 'brand image',
        'brand manager', 'brand pyramid', 'brand value', 'branding', 'branding strategy',
        'break through the clutter', 'breakneck', 'breakout', 'breakthrough', 'brick-and-mortar',
        'bricks-and-clicks', 'bring to the table', 'bring your own device', 'broaden', 'broader thinking', 'build',
        'build winning teams', 'bullet-proof', 'business case', 'business development', 'business enabling',
        'business equation', 'business leaders', 'business line', 'business model', 'business philosophy',
        'business platform', 'business-for-business', 'business-led', 'buzzword compliant',
        'expanding boundaries', 'levelling the playing field', 'leveraging', 'nurturing talent',
        'thinking and acting beyond boundaries', 'thinking outside of the box', 'calibrate', 'calibration',
        'capability', 'capitalize on', 'carefully', 'carefully thought-out', 'cascading', 'case study',
        'catalyst for growth', 'catalysts for change', 'category manager', 'cautiously', 'celebrate the success',
        'centerpiece', 'centralized', 'challenge', 'challenge established ideas', 'challenge the status quo',
        'challenging', 'challenging market conditions', 'champion', 'change', 'change management', 'channel',
        'channels', 'circle back', 'clear goal', 'clear-cut', 'clicks-and-mortar', 'clickthrough', 'client event',
        'client focus', 'client needs', 'client perspective', 'client satisfaction', 'client-based',
        'client-centered', 'client-centric', 'client-oriented', 'close the loop', 'cloud', 'co-create', 'co-develop',
        'co-innovation', 'co-opetition', 'cognitive', 'collaboration', 'collaborative', 'collateral',
        'come to a landing', 'come-to-jesus moment', 'commitment', 'common core', 'communicate', 'communication',
        'communities', 'community', 'compatible', 'compelling', 'competent', 'competently', 'competitive',
        'competitive advantage', 'competitive success', 'competitiveness', 'compliance', 'compliant',
        'comprehensive', 'concept', 'conceptualize', 'concerns', 'connect the dots',
        'connect the dots to the end game', 'connectivity', 'conservatively', 'consistency', 'consistent',
        'consistently', 'constraints', 'constructive', 'consumer-facing', 'consumer/agent disconnects', 'content',
        'context-aware', 'continual', 'continually', 'continuity', 'control', 'control information system',
        'control-based', 'controllable', 'controlled', 'conveniently', 'convergence', 'conversate', 'cooperative',
        'coordinate', 'coordinated', 'core business', 'core capacity', 'core competencies', 'core competency',
        'core meeting', 'cornerstone', 'corporate', 'corporate governance', 'corporate identity', 'correlation',
        'cost effectiveness', 'cost efficiency', 'cost reduction', 'cost savings', 'cost-competitive',
        'cost-effective', 'covalent', 'create long-term value', 'creative', 'credibility', 'credible', 'credibly',
        'critical', 'cross fertilization', 'cross-breeding', 'cross-enterprise', 'cross-functional',
        'cross-industry', 'cross-static', 'cross-platform', 'cross-sell message', 'cross-unit', 'cultivate',
        'cultivate talent', 'cultural', 'culturally', 'culture', 'curated', 'customer centricity',
        'customer directed', 'customer experience', 'customer footprint', 'customer service', 'customer-centric',
        'customer-directed', 'customer-facing', 'customer-focused', 'customized', 'cutting-edge', 'dashboard',
        'data-driven', 'day-to-day', 'decentralized', 'decision', 'decision making', 'decision-making', 'dedicated',
        'dedication', 'deep dive', 'deep web', 'deepen', 'deliver', 'deliver on commitments', 'delivery framework',
        'deploy', 'design pattern', 'design philosophy', 'develop the blue print for execution', 'develop the plan',
        'dialogue', 'differentially', 'differentiate', 'differentiated', 'differentiating', 'differentiator',
        'digital divide', 'digital economy', 'digital literacy', 'digital remastering', 'digital signage',
        'diligently', 'dinintermediate disseminate', 'discipline', 'disciplined', 'disruptive', 'distinctive',
        'distributed', 'diverse', 'diversification', 'diversifying', 'diversity', 'divisional structure', 'dna',
        'do more with less', 'do the projects right', 'do the right projects', 'do things differently', 'document',
        'document management', 'documented', 'dot-bomb', 'dotted line', 'double-digit', 'downsizing', 'downtimes',
        'dramatic', 'dramatically', 'drill down', 'drill-down', 'drinking the kool-aid', 'drive', 'drive revenue',
        'drive the business forward', 'dynamic', 'dynamics', 'e-commerce', 'e-learning', 'e-tailers', 'early-stage',
        'eating your own dogfood', 'ebitda', 'economic value creation', 'economically sound', 'ecosystem', 'edge',
        'educated', 'effective', 'effective execution', 'effectiveness', 'efficacy', 'efficiency', 'efficiency gain',
        'efficient', 'efficient frontier', 'efficiently', 'elastic', 'elite', 'embrace', 'emerging',
        'emotional impact', 'emotional intelligence', 'empower', 'empowerment', 'enable',
        'enable customer interaction', 'enabler', 'end-to-end', 'energistically', 'energize', 'energy', 'enforce',
        'engage', 'engagement', 'engineer', 'enhance', 'enhance the strength', 'enhanced', 'enhanced data capture',
        'ensuring', 'enterprise', 'enterprise content management', 'enterprise risk management', 'enterprise-wide',
        'enthusiastically', 'entitlement', 'entrepreneur', 'environment', 'envision', 'envisioneer',
        'equity invested', 'escalation', 'establish', 'established', 'ethical', 'event horizon', 'evidence-based',
        'evisculate', 'evolution', 'evolutionary', 'evolve', 'evolve our culture', 'exceed expectations',
        'excellence', 'excellent', 'exceptional', 'execute', 'execute on priorities', 'execute the strategy',
        'execution', 'executive', 'executive talent', 'executive-level', 'exit strategy',
        'expanding', 'expansion', 'expectations and allocations', 'expediently', 'expedite', 'experiences',
        'expertise', 'exploit', 'extensible', 'extensive', 'eyeballs', 'fabricate', 'face time', 'facilitate',
        'facilitators', 'fact-based', 'fairness', 'far-reaching', 'fashion', 'fast-evolving', 'fast-growth',
        'fast-track', 'feedback', 'feedback-based', 'fierce', 'figure out where we come from, where we are going to',
        'fine-grained', 'fintech', 'firm-wide', 'first-class', 'fleet dynamism', 'flesh out', 'flexibility',
        'flexible', 'flipped classroom', 'flow charting', 'focus', 'focus on', 'focus on speed', 'focused',
        'folksonomy', 'footprint', 'formulate', 'forward planning', 'forward-looking', 'forward-thinking', 'foster',
        'framework', 'franchise', 'frictionless', 'from the get-go', 'front-face', 'fuel changes',
        'fulfilment issues', 'full range of products', 'full-scale', 'fully networked', 'fully researched',
        'fully tested', 'functional', 'fungibility', 'fungible', 'fungibly', 'future', 'future-oriented',
        'future-proof', 'future-ready', 'gain in task efficiency', 'game changer', 'game changers', 'game-changing',
        'gamification', 'gaps', 'gatekeeper', 'generation x', 'generation y', 'generic', 'genuine',
        'genuinely', 'get from here to here', 'global', 'global footprint', 'global network', 'global reach',
        'global touch-base', 'globally', 'go forward', 'go forward together', 'go-to-market', 'goal', 'goal setting',
        'goal-based', 'goal-directed', 'goal-oriented', 'going forward', 'governance', 'gradually', 'granular',
        'granularity', 'granularize', 'ground-breaking', 'group', 'grow', 'grow and diversify', 'growing', 'growth',
        'growth years', 'guided reading', 'guideline', 'hashtag', 'hands-on', 'harness', 'headlights', 'headwinds',
        'healthy',
        'heart-of-the-business', 'heavy lifting', 'herding cats', 'high quality', 'high standards in',
        'high-definition', 'high-grade', 'high-growth', 'high-impact', 'high-level', 'high-margin', 'high-payoff',
        'high-performance', 'high-performing', 'high-powered', 'high-priority', 'high-quality',
        'higher-order thinking', 'highly satisfactory', 'highly-curated', 'holistic', 'human capital',
        'human resources', 'humanizing', 'hunt the business down', 'hyper-hybrid', 'hyperlocal', 'ideas', 'identify',
        'idiosyncrasy', 'idiosyncratic', 'image', 'immersion', 'immersive', 'impact', 'impactful', 'imperatives',
        'impetus', 'implementation', 'implication', 'impressive', 'improve', 'improved', 'improvement',
        'in the core', 'in the marketplace', 'in this space', 'in-depth', 'incentive', 'incentivise', 'incentivize',
        'increase customer satisfaction', 'increase in margins', 'incremental', 'incubate', 'industry',
        'industry-standard', 'inefficiencies', 'inexpensive', 'influence', 'infomediaries', 'information overloads',
        'information-age', 'informationalization', 'informed', 'infrastructure', 'ingenious', 'ingenuity',
        'initiate', 'initiative', 'initiatives', 'innovate', 'innovation', 'innovation-driven', 'innovative',
        'innovative edge', 'innovativeness', 'innovator', 'insight', 'insight-based', 'insightful',
        'insightfulness', 'inspirational', 'inspire', 'inspiring', 'installed base', 'institutionalize', 'integrate',
        'integrated', 'integration', 'integrative', 'integrativeness', 'integrity', 'intellect',
        'intellectual capital', 'intelligence', 'intelligent', 'inter-company', 'interact with', 'interactive',
        'interactively', 'interconnected', 'interdependency', 'interdependent', 'interfaces', 'intermandated',
        'internal client', 'internet of things', 'interoperability', 'interoperable', 'interpersonal skills',
        'intra-company', 'intra-organisational', 'intricacies', 'intrinsically', 'intuitive', 'intuitiveness',
        'inventory-planning', 'invested in', 'investor confidence', 'invigorate', 'issues', 'iterate',
        'jaw-dropping', 'jump-start', 'just in time', 'keep it on the radar', 'key people',
        'key performance indicators', 'key representatives', 'key target markets', 'kick-off',
        'knowledge management', 'knowledge sharing', 'knowledge transfer', 'knowledge-based', 'known unknowns',
        'landscape', 'large-scale', 'laser-focused', 'leadership', 'leadership development system',
        'leadership strategy', 'leading', 'leading-edge', 'learn', 'learnability', 'learning', 'lessons learned',
        'lever', 'leverage', 'leverage the benefits of our differentiation', 'leveraged', 'limitations',
        'line of business', 'line-of-sight', 'line-up', 'local-for-local strategy', 'location-specific', 'logistics',
        'long tail', 'long-established', 'long-running', 'long-standing', 'long-term', 'longer-term', 'loop back',
        'low hanging fruit', 'low-risk high-yield', 'machine learning', 'macroscopic', 'magnetic', 'maintain',
        'make it pop', 'make it possible', 'make the abstract concrete', 'make things happen', 'manage',
        'manage the balance', 'manage the cycle', 'manage the downside', 'manage the mix', 'manage the portfolio',
        'management information system', 'market', 'market conditions', 'market environment', 'market forces',
        'market gaps', 'market opportunities', 'market positioning', 'market practice', 'market thinker',
        'market thinkers', 'market-altering', 'market-changing', 'market-driven', 'market-driving', 'marketplace',
        'markets', 'mashup', 'materials', 'matrix', 'maximize', 'maximize the value', 'measurable', 'measure',
        'measured', 'measurement', 'mediators', 'medium-to-long-term', 'meet the challenges', 'meet the surge',
        'mesh', 'methodologies', 'methodology', 'metrics-driven', 'micro-macro', 'microsegment',
        'milestone', 'millennial', 'mind share', 'mind-blowing', 'mindful', 'mindset', 'mindshare', 'minimize',
        'mission', 'mission critical', 'mission-critical', 'mitigate', 'mobile strategies', 'models', 'modular',
        'momentum', 'monetize', 'monotonectally', 'morph', 'motivate', 'motivational', 'movable', 'move forward',
        'move the needle', 'move the progress forward', 'moving forward', 'multi-channel', 'multi-divisional',
        'multi-source', 'multi-tasked', 'multidisciplinary', 'multimedia based', 'multiple intelligences',
        'myocardinate', 'naming committee', 'negotiate', 'netiquette', 'network', 'new economy', 'new normal',
        'new-generation', 'next generation', 'next step', 'next-generation', 'next-level', 'niche', 'niches',
        'nimble', 'non-deterministic', 'non-linear', 'non-mainstream', 'non-manufacturing', 'non-standard', 'nosql',
        'number-one', 'nurture talent', 'objective', 'objectively', 'obstacles', 'offshoring', 'omni-channel',
        'on a day-to-day basis', 'on a transitional basis', 'on the runway', 'on-boarding process', 'on-demand',
        'on-message', 'on-the-fly', 'onboarding solution', 'one-on-one', 'one-to-one', 'open', 'open-door policy',
        'openness', 'operating strategy', 'operationalize', 'opportunities', 'opportunity', 'optimal', 'optimize',
        'optionality', 'options', 'orchestrate', 'organic', 'organization-wide', 'organizational',
        'organizational diseconomies', 'organizing principles', 'orthogonal', 'out-of-the-box', 'outperform peers',
        'outside the box', 'outside-in', 'outsourced', 'outsourcing', 'outstanding', 'outward-looking',
        'over the long term', 'overarching', 'overcome', 'overdeliver', 'overlaps', 'ownership', 'paas',
        'pain point', 'pandemic', 'paradigm', 'paradigm shift', 'parallel', 'paralysis by analysis', 'partners',
        'partnership', 'partnerships', 'passionate', 'peel the onion', 'performance', 'performance based',
        'performance culture', 'performance-based', 'personalized', 'perspective', 'phased', 'philosophy',
        'phosfluorescently', 'pillar', 'pioneers', 'pipeline', 'pitfalls', 'plagiarize',
        'planning granularity', 'platform', 'platforms', 'plug-and-play', 'pockets of opportunities', 'policy',
        'policy makers', 'political capital', 'pontificate', 'portal', 'portals', 'portfolio shaping', 'potential',
        'potentialities', 'potentiate', 'powerful', 'powerful champion', 'pre-approved', 'pre-integrated',
        'pre-plan', 'pre-prepare', 'predictability', 'predominate', 'preemptive', 'premier', 'premium',
        'present-day', 'principle-based', 'principle-centered', 'prioritize', 'prioritizing', 'priority',
        'proactive', 'proactively', 'problem-solving', 'problems', 'problems/difficulties', 'process',
        'process-centric', 'procrastinate', 'product manager', 'productive', 'productivity improvement',
        'professional', 'profile', 'profit center', 'profit-maximizing', 'profit-oriented', 'profitable',
        'progressive', 'project leader', 'project-based learning', 'projection',
        'promising', 'promote', 'prospective', 'proven', 'provide access to', 'pursue',
        'push the envelope', 'push the envelope to the tilt', 'pyramid', 'quality', 'quality assurance',
        'quality management system', 'quality research', 'quality-oriented', 'quarter results', 'quest for quality',
        'quickly', 'radical', 'rapid', 'rapidiously', 're-aggregate', 're-imagine', 're-imagined', 'reach out',
        'real-time', 'realignment', 'reality-based', 'reaped from our', 'rebalance', 'recalibration',
        'recaptiualize', 'recognition', 'reconceptualize', 'recurring', 'redefine', 'reintermediate', 'reinvent',
        'reinvest in', 'relationship', 'relationships', 'relevant', 'reliable', 'repurpose', 'reputation',
        'requests / solutions', 'requirement', 'reset the benchmark', 'resiliency', 'resilient', 'resource',
        'resource-leveling', 'resource-maximizing', 'resourcefulness', 'respect', 'responsibility', 'responsible',
        'responsive', 'responsiveness', 'restore', 'result in', 'result-driven', 'resulting in', 'results-centric',
        'results-oriented', 'return on investment', 'revealing', 'reverse fulfilment', 'review cycle', 'revolition',
        'revolutionary', 'revolutionise', 'revolutionize', 'reward', 'right', 'right-scale', 'right-shore',
        'right-size', 'rightshoring', 'rise to the challenge', 'risk appetite', 'risk management', 'risk taking',
        'risk/return profile', 'roadmap', 'robust', 'robustify', 'rocess improvements', 'rock-solid', 'roe', 'roi',
        'role building', 'roles and responsibilities', 'roll-out', 'rollout plan',
        'sales target', 'say/do ratio', 'scalability', 'scalable', 'scale', 'scale-as-you-grow', 'scaling',
        'scenario-based', 'scenarios', 'schemas', 'science-based', 'scoping', 'scrums', 'sea change', 'seamless',
        'seamlessly', 'secure', 'see around the corner', 'segmentation', 'seize', 'selective', 'selectivity',
        'self-awareness', 'self-efficacy', 'senior support staff', 'sensorization', 'serum', 'service-oriented',
        'serviceability', 'services', 'share options', 'shareholder value', 'shift in value', 'shoot it over',
        'shortcomings', 'shortfalls', 'showcase', 'sign-off', 'significant', 'significantly', 'siloed', 'simplicity',
        'single-minded', 'sisterhood', 'situational', 'six-sigma', 'sizeable', 'skill', 'skillset',
        'smooth transition', 'social bookmarking', 'social implications', 'social software', 'social sphere',
        'socially conscious', 'socially enabled', 'soft cycle issues', 'solid', 'solid profitability', 'solution',
        'solution orientation', 'solution provider', 'solution-oriented', 'solutions-based', 'sources', 'sox',
        'specific', 'specification quality', 'spectral', 'speedup', 'sphere', 'spin-up', 'sprints', 'stakeholder',
        'stand out from the crowd', 'stand-alone', 'standard-setters', 'standardization', 'standardize',
        'standardized', 'standards compliant', 'startup', 'state of the art', 'state-of-the-art', 'stay ahead',
        'stay in the mix', 'stay in the wings', 'stay in the zone', 'stay on trend', 'steering committee', 'stellar',
        'sticky', 'storytelling', 'straightforwardly', 'strategic', 'strategic management system',
        'strategic staircase', 'strategic thinking', 'strategically', 'strategize', 'strategy',
        'strategy formulation', 'strategy-focused', 'streamline', 'streamline the process', 'streamlined',
        'streamlining', 'strengthen', 'stress management', 'stretch our data bucket', 'stretch the status quo',
        'structural', 'structured', 'style guidelines', 'subpar returns', 'success factor',
        'successful execution', 'superior', 'superior-quality', 'supply', 'supply-chain', 'support structure',
        'surge ahead', 'surprises', 'survival strategy', 'sustainability', 'sustainable', 'sustained', 'swiftly',
        'swim lanes', 'swot analysis', 'sync-up', 'synchronized', 'syndicate', 'synergistic', 'synergize', 'synergy',
        'synthesize', 'systematized', 'systems', 'table', 'tactical', 'tactics', 'tagging',
        'take a bite out of', 'take control', 'take control of', 'take it offline', 'take offline',
        'taking advantage of', 'talent', 'talent relationship management', 'talent retention', 'target', 'targeted',
        'task-oriented', 'team building', 'team players', 'teamwork', 'teamwork-oriented', 'technical excellence',
        'technical strength', 'technically', 'technically sound', 'technological', 'technological masturbation',
        'technologies', 'technology', 'technology-centered', 'technology-driven', 'testing procedures',
        'think across the full value chain', 'think differently', 'think out of the box', 'thinkers/planners',
        'thought leader', 'thought leaders', 'thought leadership', 'thought-provoking', 'threats',
        'throughout the organization', 'throughput increase', 'time-honored', 'time-phase', 'time-phased',
        'time-to-market', 'time-to-value', 'timeline', 'timely', 'tolerably expensive', 'top', 'top-class',
        'top-down', 'top-level', 'top-line', 'total linkage', 'touchpoint', 'traceable', 'transfer', 'transform',
        'transformation process', 'transformational', 'transformative', 'transition', 'transitional', 'transmedia',
        'transparency', 'transparent', 'trend', 'tri-face', 'trigger event', 'trust-based', 'trusted',
        'trustworthy', 'turbocharge', 'turn every stone', 'turn-key', 'turnkey', 'ubiquitous', 'uncertainties',
        'under-the-radar', 'underlying', 'underperforming areas', 'underwhelm', 'unfavorable developments',
        'unified', 'uniformity', 'unique', 'unknown unknowns', 'unleash', 'unpack', 'unparalleled', 'unprecedented',
        'up, down and across the', 'up-front', 'up-sell message', 'upper single-digit', 'upside focus',
        'usage-based', 'user friendly', 'user-centric', 'users', 'utilize', 'validation', 'value',
        'value chain', 'value creation', 'value creation goals', 'value proposition', 'value realization',
        'value-added', 'value-adding', 'value-driven', 'value-enhancing', 'values congruence', 'values-based',
        'verifiable', 'versatile', 'vertical', 'viral', 'visibility', 'vision', 'vision-setting',
        'visionary', 'visual thinking', 'visualize', 'vital', 'vlogging', 'vortal', 'water under the bridge',
        'weaknesses', 'web 2.0', 'web-readiness', 'weblog', 'well-communicated', 'well-crafted', 'well-defined',
        'well-implemented', 'well-planned', 'well-positioned', 'well-scoped', 'wellness', 'wheelhouse',
        'white paper', 'white-collar efficiency', 'white-collar productivity', 'white-collar workers',
        'white-collar workforce', 'whiteboard', 'wide-ranging', 'wide-spectrum', 'wikiality', 'win-win',
        'win-win solution', 'winning', 'wins', 'within the', 'within the industry', 'workflow', 'workshops',
        'world-class', 'wow factor', 'yield enhancement']
}
