# Generated by Django 2.0.2 on 2018-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('buzzified_key', models.CharField(max_length=2000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_redirected_at', models.DateTimeField(null=True)),
                ('redirects_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'URL pair',
                'verbose_name_plural': 'URL pair',
            },
        ),
    ]
