# Generated by Django 2.2 on 2019-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpair',
            name='original_url',
            field=models.URLField(),
        ),
    ]
